name: ✅ Unit Tests

on:
  push:
    branches:
      - main
      - ci

  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['6.6.2']
        build_type: ['Release']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      -
        name: ⬇ Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.version }}
          cache: true
      -
        name: 🔧 NetTcpJson
        run: |
          cmake -E make_directory build
          cmake -DNETTCPJSON_ENABLE_TESTS=ON \
                -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
                -B build -S .
        shell: bash
      -
        name: 🔨 NetTcpJson
        run: cmake --build build --target "NetTcpJson" --config "${{ matrix.build_type }}" -j 8
      -
        name: 🔨 NetTcpJsonTests
        run: cmake --build build --target "NetTcpJsonTests" --config "${{ matrix.build_type }}" -j 8
      -
        name: ✅ Unit Tests
        run: cd build && ctest --build-config "${{ matrix.build_type }}" --progress --verbose
